### ISSUE TITLE
Where can I find the CDR data (timestamp, hashed_user_name, cellid etc.)?

### ISSUE THREAD

**Issue by NoamGit** [rmaestre/d4d-challenge#1]

**Comment by laoreja** [comment]
Same question here

**Comment by rmaestre** [comment]
Dataset is published on Nature (https://www.nature.com/articles/sdata2018286), therefore is under Data Use Agreement (DUA). https://www.researchgate.net/post/I_need_the_D4D_Challenge_dataset_CDR_data_Anybody_has_already_downloaded_it
